### PR TITLE
update TestHelper release configuration

### PR DESCRIPTION
**Pull request by gmartin7**
PlatformTarget -> AnyCPU

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/38)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: but can you figure out why the Jenkins build failed? Maybe retry?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-:-KiBYv3Fxoer0jAtTrLH:bubmhwf)*

**Comment by gmartin7** [comment]
Retry didn't work. Looking...

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-:-KiBaRjirrEd_q6pes8v:b41p379)*

**Comment by ermshiperete** [comment]
@gmartin7: I just had a look because it didn't look related to your change. However it turns out that it is related: we run NUnit as 32-bit process when run from the command line. Therefore we copy the 32-bit binaries around for the tests. However, when the test starts the TestHelper executable (compiled with AnyCPU) it'll start as 64-bit process on 64-bit Windows and so it can't find the ICU binaries.

I can see a few solutions:
a) change TestHelper.csproj back to x86 (but should then also change it for the Debug configuration). We probably should also add a check (and comment) to TestHelper.Main that it runs as 32-bit (can be detected by `IntPtr.Size != 8` and if not throw an exception

b) run the tests as 64-bit. This can be achieved by editing icu-dotnet.proj and changing the property that forces 32-bit.

**Comment by gmartin7** [comment]
Trying option b.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-:-KiG9x1S5SGjTgZVg7vS:blf19nn)*

**Comment by ermshiperete** [comment]
one minor suggestion, but otherwise looks good

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/icu-dotnet.proj, line 6 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-KiGCqSK0Ra9Nitq4DM1:-KiGCqSLcmyNSJkiutTY:bj2ah5u) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/84ea4f1866d42fb396c5f53e759283f3f2c26600/build/icu-dotnet.proj#L6)):*
> ```
> 		<RootDir Condition="'$(teamcity_version)' != '' And '$(OS)'=='Windows_NT'">$(teamcity_build_checkoutDir)</RootDir>
> 		<useNUnit-x86 Condition="'$(OS)'=='Windows_NT'">false</useNUnit-x86>
> 		<useNUnit-x86 Condition="'$(OS)'!='Windows_NT'">false</useNUnit-x86>
> ```

Those two lines could now be combined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-:-KiGC_zXAfV2ybjvjVW_:b-ep0fze)*

**Comment by gmartin7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/icu-dotnet.proj, line 6 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-KiGCqSK0Ra9Nitq4DM1:-KiGEFXsnlWD_ta_qQET:b-3sfxtp) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/84ea4f1866d42fb396c5f53e759283f3f2c26600/build/icu-dotnet.proj#L6)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Those two lines could now be combined.
</blockquote></details>

Removed property altogether.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/38#-:-KiGEK2craI2ufJTX2na:bnfp4nl)*

**Pull request merged**
