### PR TITLE
Adding ability to build icu nuget package

### LINKED ISSUE #7: Create/upload a NuGet package
I am working a on C# project that utilises ICU4C and it would be a lot easier to integrate this library in my project if I can consume it as a nuget package.

I was wondering if there are any plans to:
* Create a nupkg from the library 
* Upload the nuget package to a nuget feed (ie. https://www.nuget.org/ or https://myget.org)

I have done the work (to package this library as a nuget pkg) on a private branch but am wondering how to incorporate it in your build if your team wants this feature (or just upload a single package to a nuget feed).

Thanks,
Connie

### PR DESCRIPTION
**Pull request by conniey**
This adds the ability to create a nuget package.  There still needs to be some manual steps to be done in order to incorporate this into your build system.

**Example:** 
`nuget.exe pack bld\nuget\icu.net.nuspec -Version $(VERSION_NUMBER) -Prop Configuration=$(Configuration)`

**Manual Steps**
1. Add [nuget pack](https://confluence.jetbrains.com/display/TCD9/NuGet+Pack) publish step to build
2. Someone would have to publish the nuget package. 
    1. It could be added as a [publish step](https://confluence.jetbrains.com/display/TCD9/NuGet+Publish) in a release build.
    2. Someone could manually upload a package on [nuget.org](https://www.nuget.org/)

Fixes #7

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/10)

### CODE REVIEW

**Comment by ermshiperete** [comment]
ok to test

**Comment by FarmerPickles** [comment]
Can one of the admins verify this patch?

**Comment by FarmerPickles** [comment]
Can one of the admins verify this patch?

**Comment by conniey** [comment]
Hi, Is there anything I need to do to get this PR merged?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/10#-:-KR-iBDT_QLdq7CKUDiS:besf9id)*

**Comment by ermshiperete** [comment]
Thanks for the patch! I applied it to the master branch and made some additional changes for Linux.

**Pull request closed without merging**
