### PR TITLE
Upgrading project to icu56

### PR DESCRIPTION
**Pull request by conniey**
* Upgrades default icu version to 56
* Adds extra tests for chinese

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/6)

### CODE REVIEW

**Comment by ermshiperete** [comment]
:LGTM:

<details><summary><i>Previously, conniey wrote…</i></summary>
> #### Upgrading project to icu56
> 
> * Upgrades default icu version to 56
> 
> * Adds extra tests for chinese
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[source/icu.net.tests/icu.net.tests.csproj, line 110 \[r1\]](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6#-KIY1EpxqGk3j8sXws3d:-KIY1Epy29-yCt2iYhI6:154423926) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/18006ad978ca70bca8a6b9f99d953de9fdd25655/source/icu.net.tests/icu.net.tests.csproj#L110)):*
> ```XML
> 	<DefineConstants>$(DefineConstants);ICU_VER_$(icu_ver)</DefineConstants>
> 	<OutputPath>..\..\output\$(Configuration)</OutputPath>
>   </PropertyGroup>
> ```

I like this refactoring!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6#-:-KIY1v8gHGUh_9R3U79v:1386550993)*

**Comment by andrew-polk** [comment]
This changes the default from 54 to 56 but there is no change to download the 56 dlls (buildupdate.win.sh).

**Comment by conniey** [comment]
@andrew-polk : Thanks for pointing this out! I've updated it.

Is there any way I can test the build steps locally? I want to make sure I don't break your build.

**Comment by andrew-polk** [comment]
I should have clarified. buildupdate.win.sh is generated and should not be modified manually. It is generated using the tool at https://github.com/chrisvire/BuildUpdate based on the dependencies of the TeamCity build of icu-dotnet. That means someone on the team needs to change the dependencies on TeamCity, then buildupdate.win.sh needs to be regenerated. But it's rather a chicken and egg problem.

@ermshiperete, do you have a suggestion as to the best way to handle this?

**Comment by ermshiperete** [comment]
@andrew-polk Yes, that _is_ a chicken and egg problem. I have a different solution that I hope to present at our LSDev conference. 

But then there's still the problem that we need consent to upgrade to 56 on the Windows side (the Linux side is handled differently, so there's no problem there).

If we do the update to 56 we'd have to:

-  on Windows (manually) build ICU 56 instead of 54, following the steps outlined in icu-dotnet readme
- change the icu4c-win32-minimal build job on TC to download ICU 56 instead of 54
- adjust dependencies of icucil-win32-default Continuous to the *56* filenames
- regenerate bld/buildupdate.win.sh script

@conniey Currently there's no easy way to reproduce the build that TeamCity does. The TC build runs `msbuild` with the `Test` target on `bld/build.proj`, but I doubt that this will work outside of TC. I'll try to make some improvements in the near future so that we can use the same build steps on a developer's machine.

<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I should have clarified. buildupdate.win.sh is generated and should not be modified manually. It is generated using the tool at https://github.com/chrisvire/BuildUpdate based on the dependencies of the TeamCity build of icu-dotnet. That means someone on the team needs to change the dependencies on TeamCity, then buildupdate.win.sh needs to be regenerated. But it's rather a chicken and egg problem.
> 
> 
> 
> @ermshiperete, do you have a suggestion as to the best way to handle this?
</details>


---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6#-:-KJ08Xv7H7NY2Sb12Wml:-1245728256)*

**Comment by ermshiperete** [comment]
> Is there any way I can test the build steps locally? I want to make sure I don't break your build.

@conniey, I finally got around to improve the build. It is now possible to run the same build as TC/Jenkins does. See the updated README.md for details.

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6#-:-KMPkUJNafl-iF-ZXahf:1948745929)*

**Comment by FarmerPickles** [comment]
Can one of the admins verify this patch?

**Comment by FarmerPickles** [comment]
Can one of the admins verify this patch?

**Comment by ermshiperete** [comment]
ok to test

**Comment by ermshiperete** [comment]
ok to test

**Comment by conniey** [comment]
@ermshiperete I updated my PR based on the latest changes to the build.  I created a minimal build for 56.1 using the instructions from the README.md.  You can download it here: [icu4c-56.1-win32-min.zip](https://1drv.ms/u/s!AlGDh95zLvCeiJgU3bv172ayJ6Gcow)

I tried to follow the steps to update Dependencies.files but the BuildDependencyManager project from [your repository](https://github.com/ermshiperete/BuildDependency) does not build for me (and I am not sure how to use it).

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6#-:-KR4nwDaE2dNjb0TqZzQ:b-aprlnw)*

**Comment by ermshiperete** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/6)*

**Comment by ermshiperete** [comment]
@conniey Thanks for your contribution!

I created a TC build for [minimial statically linked ICU 56](http://build.palaso.org/viewType.html?buildTypeId=Libraries_Icu4c56win32minimumStaticallyLinkedContinuous).

I applied some of your commits to the `master` branch and created a new `icu56` branch - I'd like to do some more testing before we make that the general default. I updated the dependencies on that branch so that it downloads the icu56 dlls, and created a [TC build](http://build.palaso.org/viewType.html?buildTypeId=Libraries_IcucilWin32icu56Continuous) for the icu56 branch which should also create nuget packages.

**Comment by conniey** [comment]
@ermshiperete 

> What errors do you get when you try to build it [BuildDependencyManager]?

I cloned the repository and tried to run a `nuget restore .\BuildDependency.sln` and get the following errors because it can't find GitVersionTask v4.0.1 on NuGet.org. Is this package on another feed?

```
Errors in packages.config projects
    Unable to find version '4.0.1' of package 'GitVersionTask'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'GitVersionTask.4.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      C:\Users\conniey\.nuget\packages\: Package 'GitVersionTask.4.0.1' is not found on source 'C:\Users\conniey\.nuget\packages\'.
      C:\Users\conniey\AppData\Local\NuGet\Cache: Package 'GitVersionTask.4.0.1' is not found on source 'C:\Users\conniey\AppData\Local\NuGet\Cache'.
      https://api.nuget.org/v3/index.json: Package 'GitVersionTask.4.0.1' is not found on source 'https://api.nuget.org/v3/index.json'.
```

**Comment by ermshiperete** [comment]
@conniey Yes, sorry, that package was available only locally on my machine. Now that an official 4.0 GitVersionTask package is available I just pushed a change to use that, so hopefully things should build now :smiley:

**Pull request closed without merging**
