### PR TITLE
Implement Transliterator.{CreateInstance, Transliterate}

### PR DESCRIPTION
**Pull request by tylerpayne**
ICU's "Any-Latin; Latin-ASCII" transliteration is my most desired feature. This change moves towards an actual implementation of the Transliterator class.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/131)

### CODE REVIEW

**Review by ermshiperete — CHANGES_REQUESTED** [review]
Thanks for your contribution!

I have a few minor comments that I'd like to see addressed (or discussed).

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-:-MLhCGv3-cJiDYOUigXY:b-hwgfhw)* status: all files reviewed, 4 unresolved discussions (waiting on @tylerpayne)

___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 20 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLgkcdP4oVCsfGLF2Da:-MLgkcdP4oVCsfGLF2Db:b-plai02) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/86cbf624c53647a2e6e6b418fd4ee63f8bd0043a/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L20)):*
> ```Smalltalk
> 			/// <summary/>
> 			[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
> 			internal delegate Transliterator utrans_openDelegate(string id, UTransDirection dir, string rules, int rulesLength, out ParseError parseError, out ErrorCode status);
> ```

`utrans_open` is deprecated, so it would be better to use `utrans_openU` instead.
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 52 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLglCcR2jIvPpc90kZ3:-MLglCcR2jIvPpc90kZ4:bzfl8gz) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/86cbf624c53647a2e6e6b418fd4ee63f8bd0043a/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L52)):*
> ```Smalltalk
> 
> 		/// <summary />
> 		public static Transliterator utrans_open(string id, UTransDirection dir, out ParseError parseError, out ErrorCode status)
> ```

Please add the `rules` parameter as well.

Rename to `utrans_openU` (signature can remain the same)
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 73 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLgnNPm1TKW9BA17KZM:-MLgnNPnEYb2vn-VnKwn:bs0rxhk) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/86cbf624c53647a2e6e6b418fd4ee63f8bd0043a/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L73)):*
> ```
> int textLength
> ```

Since this is an in/out parameter in C++, this should be `ref int textLength`. Same for `limit`.
___
*[source/icu.net.tests/TransliteratorTests.cs, line 33 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLhAIrv1JzpzReCamB0:-MLhAIrv1JzpzReCamB1:bxvy6tf) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/86cbf624c53647a2e6e6b418fd4ee63f8bd0043a/source/icu.net.tests/TransliteratorTests.cs#L33)):*
> ```Smalltalk
> 		public void OpenSingleId()
> 		{
> 			Transliterator.CreateInstance(@"Any-Latin");
> ```

The created object has to be disposed otherwise the tests may hang, especially on Linux. I'd add a teardown method to dispose the transliterator (if created).

Also, the test could be improved so that it's obvious what we're testing by surrounding the `CreateInstance` with `Assert.That(...., Throw.Nothing)`.

Same for the next two tests below.

For example:

```csharp
		private Transliterator _transliterator;

		[TearDown]
		public void TearDown()
		{
			_transliterator?.Dispose();
			_transliterator = null;
		}

...

		[Test]
		public void OpenSingleId()
		{
			Assert.That(() => _transliterator = Transliterator.CreateInstance(@"Any-Latin"), Throws.Nothing);
		}

```
___
*[source/icu.net.tests/TransliteratorTests.cs, line 57 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLhB_sT40Uny3RAEECX:-MLhB_sT40Uny3RAEECY:bcgerqd) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/86cbf624c53647a2e6e6b418fd4ee63f8bd0043a/source/icu.net.tests/TransliteratorTests.cs#L57)):*
> ```Smalltalk
> 
> 			Assert.That(trans.Transliterate(source), Is.EqualTo(target));
> 		}
> ```

I wonder if the marshalling works correctly if transliteration extends/shrinks the string. Some tests for that would be nice (but not necessarily required for this PR).

**Comment by tylerpayne** [comment]
Thanks for the review. See latest commit for updates.

> I wonder if the marshalling works correctly if transliteration extends/shrinks the string. Some tests for that would be nice (but not necessarily required for this PR).

I included a test, [TransliterateLonger](https://github.com/rivaltheory/icu-dotnet/blob/43bc618abacfa0e4ac64ba6c05a441f96eeb33a8/source/icu.net.tests/TransliteratorTests.cs#L84), that demonstrates that the string extending does in fact cause marshaling issues. I attempted to marshal the memory via raw IntPtr's with unicode bytes but repeatedly ran into issues. I imagine there are other places where you have to marshal a `string` to a `UChar *` and I'm hoping you can advise on the correct way to do this.

**Comment by tylerpayne** [comment]
Fixed the TransliterateLonger issue (up to 2x the input string's length, may want to make this a parameter)

**Review by ermshiperete — CHANGES_REQUESTED** [review]
Great! Thanks for the changes. Unfortunately I found a few problems in `utrans_transUChars`.

Also, can you please rebase or merge with master? I believe this will fix the problems building this PR on the CI server.

> Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-:-MLm2FZ55rEsODkx0uhz:b-7ui4mw)* status: all files reviewed, 7 unresolved discussions (waiting on @tylerpayne)

___
*[source/icu.net/Transliterator.cs, line 261 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlsTOR9uGyTbk3QbAJ:-MLlsTOR9uGyTbk3QbAK:b-ubr67r) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net/Transliterator.cs#L261)):*
> ```
> truncated to `text.Length` characters
> ```

This doesn't seem to be true. Suggestion: 

```
The transliterated text, truncated to `text.Length` * 2 characters.
```
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 83 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlsldh2qffOVWk77_y:-MLlsldh2qffOVWk77_z:bkbgvfh) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L83)):*
> ```
> unicodeBytes.Length / 2
> ```

Why not just use `text.Length`?

Otherwise it would be better to use `Marshal.SystemDefaultCharSize` instead of hard-coding the value 2 (not that it changes anything, but IMO it's easier to understand).
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 84 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlihEy0J3FlfZt1yri:-MLlihEy0J3FlfZt1yrj:b-6jmhz7) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L84)):*
> ```
> textLength * 2 + 1
> ```

This doesn't look right - this says that we have capacity for `textLength * 2 + 1` characters, so we would have to allocate `(textLength * 2 + 1) * 2` bytes. The current implementation causes a buffer overrun.
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 88 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLm-ffW7QvZ2AsrWTDP:-MLm-ffW7QvZ2AsrWTDQ:bn25uug) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L88)):*
> ```Smalltalk
> 			int limit = textLength;
> 
> 			IntPtr textPtr = Marshal.AllocHGlobal(unicodeBytes.Length * 2);
> ```

I think we should allocate twice the size of the original string, which would be `textCapacity * Marshal.SystemDefaultCharSize`. `textCapacity` can then be set to `2 * text.Length`.
___
*[source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlp_Pt0Iwtu4SSrolk:-MLlp_Pt0Iwtu4SSroll:b-qhxk0j) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net/NativeMethods/NativeMethods_Transliterator.cs#L94)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			unicodeBytes = new byte[2 * textLength];
> 			for (int ofs = 0; ofs < unicodeBytes.Length; ofs++)
> 				unicodeBytes[ofs] = Marshal.ReadByte(textPtr, ofs);
> 			string result = Encoding.Unicode.GetString(unicodeBytes);
> ```
</details>


Can't we use `result = Marshal.PtrToStringUni(textPtr, textLength)` ?
___
*[source/icu.net.tests/TransliteratorTests.cs, line 13 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlk-T6B5-8HEgdGA_x:-MLlk-T6B5-8HEgdGA_y:btwotgt) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net.tests/TransliteratorTests.cs#L13)):*
> ```Smalltalk
> 		Transliterator _transSingle = null, _transCompound = null;
> 
> 		[Test, Order(1)]
> ```

Ah - learned something new. Didn't know about the `Order` attribute until now :smile: 
___
*[source/icu.net.tests/TransliteratorTests.cs, line 45 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLllPbJ1IlysFcGQTrJ:-MLllPbJ1IlysFcGQTrK:b-y4v12s) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net.tests/TransliteratorTests.cs#L45)):*
> ```Smalltalk
> 		public void OpenSingleId()
> 		{
> 			Assert.DoesNotThrow(() => MaybeOpenSingle(true));
> ```

I'm happy to merge with the tests being like this, but I'm wondering why you decided to add separate variables for single and compound? IMO adding the `MaybeOpenSingle`/`MaybeOpenCompound` methods hides what we're actually testing and makes the tests harder to understand. Also, why is it necessary to dispose `_transSingle`/`_transCompound` before creating a transliterator? Isn't this taken care of by the `TearDown` method that runs after each test? I'm probably missing something...
___
*[source/icu.net.tests/TransliteratorTests.cs, line 84 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLllLNc07YJjSRrp3mM:-MLllLNc07YJjSRrp3mN:b-vhk9az) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net.tests/TransliteratorTests.cs#L84)):*
> ```Smalltalk
> 
> 		[Test, Order(3)]
> 		public void TransliterateLonger()
> ```

:+1:  Great that you added a test for this!
___
*[source/icu.net.tests/TransliteratorTests.cs, line 95 at r4](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-MLlkmFn6kl8gs64RWxe:-MLlkmFn6kl8gs64RWxf:bk3st1f) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/c969d0e5b0dba9d0065375c94a4f45be7d97ec53/source/icu.net.tests/TransliteratorTests.cs#L95)):*
> ```Smalltalk
> 
> 		[TearDown]
> 		public void TearDown()
> ```

nit: can you move this method to the top of the file please? That's where we usually have it and look for it.

**Comment by tylerpayne** [comment]
Thanks again for the detailed review. I've rebased against your master, hopefully that resolves the CI build.

>This doesn't seem to be true. Suggestion:
> ```The transliterated text, truncated to `text.Length` * 2 characters.```

That was sloppy on my part, thanks for catching it.

> I found a few problems in utrans_transUChars

I agree with all of your suggestions for `utrans_transUChars` I've implemented them. The only reason I wasn't using PtrToStringUni was because I assumed transUChars wouldn't null-terminate the transliterated text. That does seem to be true, but is easily solved by only returning the appropriate substring.

I've also made the textCapacity multiplier a parameter (`textCapacityMultipler`). I believe it is the responsibility of the caller to know how much longer their transliterated text may be. For example Greek is almost 1x whereas Chinese is probably closer to 4x.

> but I'm wondering why you decided to add separate variables for single and compound

This was a misunderstanding on my part of TextFixture, Test, and TearDown. I though TearDown was called at the end of the whole TextFixture. I see now it happens after each Test, I've updated the tests accordingly.

**Review by ermshiperete — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/131#-:-MLnGc_H3wzTgVI6s5w5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tylerpayne)

**Comment by ermshiperete** [comment]
Merged slightly modified version to `master` as 66f4c3360aaa132c0713107836f10c30b1501b9a (PR #133).

Thanks again!

**Pull request closed without merging**
