### PR TITLE
Fix loading of native binary from directory with spaces in the path

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/26)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[source/icu.net.tests/NativeMethodsTests.cs, line 27 at r1](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26#-KZ7bTrR5_H3QU6wxb4M:-KZ7bTrR5_H3QU6wxb4N:b9iu733) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6e75d7d5983914bf1e29d912c83fbf26767b65fa/source/icu.net.tests/NativeMethodsTests.cs#L27)):*
> ```Smalltalk
> 		private static string OutputDirectory
> 		{
> 			get { return Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().CodeBase).AbsolutePath); }
> ```

This will fail if a developer has spaces in their project path in the same way that the real code failed at runtime.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26)*

**Comment by jasonleenaylor** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26)*

**Comment by ermshiperete** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[source/icu.net.tests/NativeMethodsTests.cs, line 27 at r1](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26#-KZ7bTrR5_H3QU6wxb4M:-KZ7c1r-2dg5cf8WReoQ:b-c7zzzu) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6e75d7d5983914bf1e29d912c83fbf26767b65fa/source/icu.net.tests/NativeMethodsTests.cs#L27)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This will fail if a developer has spaces in their project path in the same way that the real code failed at runtime.
</blockquote></details>

Stink. Yes, of course. I knew that `AbsolutePath` was used somewhere else, but I forgot to check. Thanks for noticing this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26)*

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26#-:-KZ7fvDL56vNcUfXnY5O:bnfp4nl)*

**Comment by jasonleenaylor** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/26)*

**Pull request merged**
