### PR TITLE
Add TimeZone class

### PR DESCRIPTION
**Pull request by j-troc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/108)

### CODE REVIEW

**Comment by j-troc** [comment]
Could you share test failure details? Link is inaccessible.

**Comment by ermshiperete** [comment]
Thanks for your contribution!

Sorry, I had intended to share the failed test, but didn't get around yet. Anyway, here it is:

```
Error Message

  Expected: 632
  But was:  621

Stacktrace

  at Icu.Tests.TimeZoneTests.GetTimeZonesTest () [0x00016] in <0ce791bf19c64c649fd393bc30a4276c>:0 
```

That's running the tests on Ubuntu 18.04; the tests succeed on Windows. I haven't looked yet if this is caused by Linux/Windows difference, or if it is caused by using a different ICU version.

**Comment by j-troc** [comment]
These changes build on my machine. What is the build error?

**Comment by ermshiperete** [comment]
Sorry, I was travelling. There was a hick-up on the server. I restarted the build and now it passed.

**Comment by j-troc** [comment]
Does the code need changes?

**Comment by ermshiperete** [comment]
Thanks @j-troc !

**Pull request merged**
