### PR TITLE
Fixed an XML comment bug by replacing < with &lt;.

### PR DESCRIPTION
**Pull request by murata0204**
This is my first pull request for icu-dotnet.  I might be able to submit more pull requests for the support of regular expressions.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/28)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/28#-:-KcvQJbrnF9qef7DhtH1:bnfp4nl)*

**Comment by ermshiperete** [comment]
ok to test

**Comment by ermshiperete** [comment]
@murata0204 Thanks for your contribution!

**Pull request merged**
