### PR TITLE
Regexp

### PR DESCRIPTION
**Pull request by murata0204**
A minimum support of regular expressions.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/35)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by ermshiperete** [comment]
Thanks for your contribution!

Can you please indent the code with tabs instead of spaces, and remove trailing space? This might be easiest done by installing or enabling a [EditorConfig](http://editorconfig.org/) plugin in your IDE and then reformat the changed code parts.

And please add some unit tests!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[source/icu.net/RegexMatcher.cs, line 18 at r1](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiG6bYkdCWNSLU_wysI:-KiG6bYkdCWNSLU_wysJ:b-hzhc7g) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/f24046a6ee51660aeddc048d1066e3c4ce31e177/source/icu.net/RegexMatcher.cs#L18)):*
> ```Smalltalk
>         /// Constants for Regular Expression Match Modes.
>         /// </summary>
>         public enum Flag: uint
> ```

I would prefer if this enum would be called something like `RegexFlag` or `URegex` and then omit `UREGEX_` from the values.

---

*[source/icu.net/RegexMatcher.cs, line 84 at r1](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiG7poTXMEm0JZZmVMS:-KiG7poUsRCKGfFV62pq:b-av737i) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/f24046a6ee51660aeddc048d1066e3c4ce31e177/source/icu.net/RegexMatcher.cs#L84)):*
> ```Smalltalk
>         /// <param name="regexp">a unicode regular expression</param>
>         /// <param name="flags">an array of flags</param>
>         public RegexMatcher(string regexp, Flag[] flags)
> ```

Why do you pass in an array of flags that you then bitOr instead of directly the or'ed flag?

That would seem more natural. It requires adding the `FlagAttribute` to `Flag`.

---

*[source/icu.net/RegexMatcher.cs, line 172 at r1](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiGA8ocuph8beSPI2cS:-KiGA8odpYQdpj6GZWqO:bhgfc3g) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/f24046a6ee51660aeddc048d1066e3c4ce31e177/source/icu.net/RegexMatcher.cs#L172)):*
> ```Smalltalk
>                 }
> 
>                 _disposingValue = true;
> ```

Setting `_disposingValue = true` should be done directly after checking `if (!_disposingValue)`, and should be reset to false here.

However, I'm not sure we need `_disposingValue` at all. It tries to prevent re-entrancy of Dispose which won't happen with what we do in Dispose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-:-KiG5lFet7vgPmwzSqe5:b-1h3jt1)*

**Comment by ermshiperete** [comment]
ok to test

**Comment by murata0204** [comment]
Thanks for review comments.  

Let me ask some questions.  First,  my Dispose function is basically 
copied from RuleBasedBreakIterator.   The sentence _disposingValue = true
appears in the same place in that class.

Second, I don't quite understand what you mean by " It requires adding 
the FlagAttribute to Flag."  Could you provide a bit more details?

**Comment by ermshiperete** [comment]
Looks like I overlooked the _disposingValue in the PR where that got introduced. That PR went through several iterations, and I guess I didn't look carefully enough before merging. We'll have to fix it there occasionally.

For the FlagsAttribute, see http://stackoverflow.com/a/8480 (sorry, should have added at least a link to [MSDN](https://msdn.microsoft.com/en-us/library/system.flagsattribute(v=vs.110).aspx) in my review comment). As it turns out it's not required to add `[Flags]` in order to be able to bitwise-or the values of the enum, but it improves the output of `ToString()` so I'd still recommend adding it - I'm learning something new every day :smiley:

**Comment by murata0204** [comment]
I improved my code accordingly.  I did not omit the UREGEX_ prefix because these enum values are borrowed from the original code.  But it is true that these are wordy.

**Comment by ermshiperete** [comment]
Thanks for updating the PR! 

I'd still prefer if you'd omit UREGEX_ to be consistent with the way we treat enums elsewhere (e.g. [UBreakIteratorType](https://github.com/sillsdev/icu-dotnet/blob/master/source/icu.net/BreakIterator.cs#L20)).

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[source/icu.net/icu.net.csproj, line 121 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVEXSOpUh7KeJw1gOE:-KiVEXSPJG8INguuciqZ:baydita) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/icu.net.csproj#L121)):*
> ```XML
>   </PropertyGroup>
>   <ItemGroup>
>     <Reference Include="nunit.framework, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
> ```

The icu.net project shouldn't have a reference to NUnit.

---

*[source/icu.net/packages.config, line 4 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVEmaRvBHqOVxrudhS:-KiVEmaRvBHqOVxrudhT:byw17uf) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="GitVersionTask" version="4.0.0-beta0009" targetFramework="net40" developmentDependency="true" />
>   <package id="NUnit" version="2.6.4" targetFramework="net40" />
> ```

icu.net shouldn't reference NUnit - unit tests belong in `icu.net.tests`

---

*[source/icu.net/RegexMatcher.cs, line 83 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVFKkjg6ZB6V5s_11X:-KiVFKkjg6ZB6V5s_11Y:b23ap6q) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/RegexMatcher.cs#L83)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="regexp">a unicode regular expression</param>
> 		/// <param name="flags">an array of flags</param>
> ```

The comment is wrong now

---

*[source/icu.net/RegexMatcher.cs, line 84 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVFNP08PlS3WPQxCUp:-KiVFNP08PlS3WPQxCUq:b-msap0e) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/RegexMatcher.cs#L84)):*
> ```Smalltalk
> 		/// <param name="regexp">a unicode regular expression</param>
> 		/// <param name="flags">an array of flags</param>
> 		public RegexMatcher(string regexp, uint flags)
> ```

`flags` should be of type `URegexpFlag`.  To account for `flags == 0` I'd add the value `None` to `URegexpFlag`.

Also, it would be convenient to add a default value to `flags` (`URegexpFlag flags = URegexpFlag.None`).

---

*[source/icu.net.tests/icu.net.tests.csproj, line 176 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVFb9bm3PXCex1ukLT:-KiVFb9bm3PXCex1ukLU:b-vu73zq) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net.tests/icu.net.tests.csproj#L176)):*
> <None Include="icu4c.readme.txt" />

Please don't remove this line - the icu4c nuget package puts it there when the nuget package gets installed.

---

*[source/icu.net.tests/RegexMatcherTests.cs, line 16 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVGcgQfLzQGmcVmyaP:-KiVGcgQfLzQGmcVmyaQ:b9justj) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net.tests/RegexMatcherTests.cs#L16)):*
> ```Smalltalk
> 		{
> 			RegexMatcher rm = new RegexMatcher("(a|b)*c", 0);
> 			Assert.That(rm.Matches("c"));
> ```

This test could be written with the [TestCase] attribute:

    [TestCase("c",  ExpectedResult = true)]
    ...
    [TestCase("ba", ExpectedResult = false)]
    ...
    public bool Match(string text)
    {
        RegexMatch rm = new RegexMatch("(a|b)*c", 0);
        return rm.Matches(text);
    }

---

*[source/icu.net.tests/RegexMatcherTests.cs, line 25 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVILx_IzqyL_aGseqc:-KiVILx_IzqyL_aGseqd:b957nin) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net.tests/RegexMatcherTests.cs#L25)):*
> ```Smalltalk
> 		}
> 		[Test]
> 		public void MatchWithCommentsAndSpace()
> ```

I don't see a comment in the pattern.

---

*[source/TestHelper/packages.config, line 5 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVIZjONjd_pMVn8FCz:-KiVIZjPds_q76UNIZCQ:b-ay0nrl) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/TestHelper/packages.config#L5)):*
> ```XML
>   <package id="NUnit" version="2.6.4" targetFramework="net40" />
>   <package id="NUnitTestAdapter" version="2.1.1" targetFramework="net40" />
> </packages>
> ```

We shouldn't need NUnit in this project.

---

*[source/TestHelper/TestHelper.csproj, line 37 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVIbxRudhLcclCIcSn:-KiVIbxRudhLcclCIcSo:b-7867xd) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/TestHelper/TestHelper.csproj#L37)):*
> ```XML
>   <ItemGroup>
>     <Reference Include="nunit.framework, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
>       <HintPath>..\packages\NUnit.2.6.4\lib\nunit.framework.dll</HintPath>
> ```

We shouldn't need NUnit in this project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-:-KiVK9bCMIDjGDHbvEQ1:b-wvadt4)*

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[source/icu.net/RegexMatcher.cs, line 19 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVNEttEI0GfSCOBLQi:-KiVNEttEI0GfSCOBLQj:bkh5sq) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/RegexMatcher.cs#L19)):*
> ```Smalltalk
> 		/// </summary>
> 		[Flags]
> 		public enum URegexpFlag : uint
> ```

I just noticed that this produces a warning CS3009. I'd suggest to simply remove `uint`.

---

*[source/icu.net/RegexMatcher.cs, line 84 at r2](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-KiVFNP08PlS3WPQxCUp:-KiVNRxE8IVzhAxdAmz_:bied13n) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a83a70c0622be667fbf359b131afba53d780c628/source/icu.net/RegexMatcher.cs#L84)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

`flags` should be of type `URegexpFlag`.  To account for `flags == 0` I'd add the value `None` to `URegexpFlag`.

Also, it would be convenient to add a default value to `flags` (`URegexpFlag flags = URegexpFlag.None`).
</blockquote></details>

In addition to my  previous comment I noticed that having the parameter of type `uint` produces a warning CS3001.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35)*

**Comment by murata0204** [comment]
Thank you very much for your advice.  I learned a lot.  Is my latest commit good enough?

**Comment by ermshiperete** [comment]
Yes, that looks good now. Thanks again for your patience and contribution!

:lgtm: 

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[source/icu.net.tests/RegexMatcherTests.cs, line 25 at r3](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-Kide43tdFBYCr4KuUxb:-Kide43tdFBYCr4KuUxc:b-1m8fnk) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/cf6a5edaf76e460d39551c85b9ce952619e35216/source/icu.net.tests/RegexMatcherTests.cs#L25)):*
> ```Smalltalk
> 			return rm.Matches(text);
> 		}
> 		[Test]
> ```

FYI: if you add the [TestCase] attribute you don't need [Test]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu-dotnet/35#-:-Kidec3IkV2jbDWEDHbc:b-20ptp4)*

**Comment by ermshiperete** [comment]
Merged slightly modified version ([6fdb981](https://github.com/sillsdev/icu-dotnet/commit/6fdb9810f8b3ea039730d6c09114615123525432)). Thanks!

**Pull request closed without merging**
